"""The measurement harness.  ⚠️  DO NOT EDIT THIS FILE.

GROUND TRUTH: every perf spec asserts against the numbers this file records,
so editing it invalidates every measurement. The correctness guards in each
spec fail anyway, because the product still has to work.

Why a fake provider at all
--------------------------
You cannot debug latency and cost against the real Gemini free tier: it's
non-deterministic, it rate-limits you mid-investigation, and a p95 measurement
over the public internet tells you about the internet, not about your code.

So we simulate the provider — but *honestly*:

  * **Latency is real.** `embed()` and `chat()` actually sleep. If you call the
    model 8 times in a row, you really do wait 8x. If you parallelize, you
    really do get the time back. Wall clock means something here.
  * **Cost is real arithmetic.** Tokens in, tokens out, priced off the same
    `settings.usd_per_1m_*` knobs the rest of the service uses.
  * **Failure is real.** 429s, 500s, 400s, hangs, and multi-minute outages are
    all injectable, so you can measure what your retry policy actually does
    instead of hoping.

The one thing that is deliberately *not* realistic: the sleeps are milliseconds
rather than seconds, so the whole spec suite runs in a few seconds. Everything
scales proportionally — a fix that halves the call count halves the wall clock,
same as production.

The batching lever
------------------
`embed()` costs ONE call and ONE network round-trip no matter how many texts
you pass (up to `MAX_BATCH`). That is exactly how real embedding APIs price and
perform, and it is the single biggest cost/latency lever in this codebase.
Embedding 50 chunks one-at-a-time is 50 round-trips; embedding them in one
batch is 1.
"""

from __future__ import annotations

import hashlib
import math
import threading
import time
from dataclasses import dataclass, field

from ..config import settings

# A real embedding endpoint takes a list and returns a list. There's a cap on
# how many you can send at once; past that you page.
MAX_BATCH = 100

# Vectors are small here so the tests stay fast. Real ones are 768+.
EMBED_DIM = 64

# Not all models cost the same, and the cheap one is not "the bad one" — it is
# the right tool for classification, routing, and yes/no guards. Sending a
# one-word judgement to the flagship model is the most common line item on a
# bill that surprised somebody.
CHEAP_COST_FACTOR = 0.2      # cheap model is 5x cheaper per token
CHEAP_LATENCY_FACTOR = 0.4   # ...and noticeably faster


class ProviderError(Exception):
    """A model-provider failure, carrying an HTTP-ish status code.

    `code` follows the usual conventions, and your retry policy should too:
      429      -> rate limited, transient, worth retrying
      500-599  -> server-side, transient, worth retrying
      400/401  -> your request or your key is wrong. Retrying changes nothing
                  and burns quota. Fail fast.
    """

    def __init__(self, message: str, *, code: int) -> None:
        super().__init__(message)
        self.code = code


@dataclass
class CallRecord:
    """One provider round-trip, as the harness saw it."""

    kind: str            # "embed" | "chat"
    model: str
    n_inputs: int        # how many texts went in (batch size for embed)
    input_tokens: int
    output_tokens: int
    usd: float
    started_at: float
    duration_s: float
    ok: bool = True
    code: int | None = None  # set when the call failed
    tag: str = ""            # free-form label, e.g. "rerank" / "answer"


def count_tokens(text: str) -> int:
    """Deterministic stand-in for a real tokenizer: ~4 characters per token."""
    return max(1, len(text) // 4)


def _is_cheap(model: str | None) -> bool:
    return bool(model) and model == settings.cheap_model


def _hashed_vector(text: str) -> list[float]:
    """A deterministic bag-of-words embedding via the hashing trick.

    Not a language model — but it has the one property retrieval depends on:
    texts that share words land near each other under cosine similarity. That
    makes search results stable and meaningful without a network call, so the
    correctness guards in the specs actually mean something.
    """
    vec = [0.0] * EMBED_DIM
    for word in text.lower().split():
        word = word.strip(".,!?;:()[]\"'`")
        if not word:
            continue
        digest = hashlib.md5(word.encode("utf-8")).digest()
        idx = digest[0] % EMBED_DIM
        sign = 1.0 if digest[1] % 2 == 0 else -1.0
        vec[idx] += sign
    norm = math.sqrt(sum(v * v for v in vec)) or 1.0
    return [v / norm for v in vec]


class FakeProvider:
    """A deterministic, instrumented, fault-injectable model provider.

    Thread-safe. Note that the simulated network delay happens *outside* the
    lock — otherwise this class would serialize your concurrency and you'd be
    measuring the harness instead of your code.
    """

    def __init__(
        self,
        *,
        embed_latency_s: float = 0.015,
        chat_latency_s: float = 0.025,
        per_1k_output_latency_s: float = 0.010,
    ) -> None:
        self.embed_latency_s = embed_latency_s
        self.chat_latency_s = chat_latency_s
        self.per_1k_output_latency_s = per_1k_output_latency_s

        self.calls: list[CallRecord] = []
        self._lock = threading.Lock()

        # --- fault injection --------------------------------------------
        self._fail_remaining = 0
        self._fail_code = 429
        self._hang_remaining = 0
        self._hang_seconds = 0.0

        # How many times a client was constructed. Rebuilding an HTTP client
        # per request throws away connection pooling.
        self.client_builds = 0

    # ------------------------------------------------------------------
    # fault injection
    # ------------------------------------------------------------------
    def fail_next(self, n: int, *, code: int = 429) -> None:
        """The next `n` calls raise ProviderError(code) before doing any work."""
        with self._lock:
            self._fail_remaining = n
            self._fail_code = code

    def hang_next(self, n: int, *, seconds: float = 5.0) -> None:
        """The next `n` calls take `seconds` to respond. Tests your timeout."""
        with self._lock:
            self._hang_remaining = n
            self._hang_seconds = seconds

    def clear_faults(self) -> None:
        with self._lock:
            self._fail_remaining = 0
            self._hang_remaining = 0

    def build_client(self) -> "FakeProvider":
        """Simulates constructing an SDK/HTTP client. Cheap to call, but each
        build means a fresh connection pool."""
        with self._lock:
            self.client_builds += 1
        return self

    # ------------------------------------------------------------------
    # the API surface the service calls
    # ------------------------------------------------------------------
    def embed(self, texts: list[str], *, task_type: str = "RETRIEVAL_DOCUMENT",
              tag: str = "") -> list[list[float]]:
        """Embed a batch. ONE round-trip regardless of batch size (<= MAX_BATCH)."""
        if len(texts) > MAX_BATCH:
            raise ProviderError(
                f"batch of {len(texts)} exceeds MAX_BATCH={MAX_BATCH}; page it",
                code=400,
            )
        input_tokens = sum(count_tokens(t) for t in texts)
        self._precheck(kind="embed", model=settings.embed_model,
                       n_inputs=len(texts), input_tokens=input_tokens, tag=tag)

        started = time.perf_counter()
        self._sleep(self.embed_latency_s)
        duration = time.perf_counter() - started

        self._record(CallRecord(
            kind="embed", model=settings.embed_model, n_inputs=len(texts),
            input_tokens=input_tokens, output_tokens=0,
            usd=self._usd(input_tokens, 0), started_at=started,
            duration_s=duration, tag=tag,
        ))
        return [_hashed_vector(t) for t in texts]

    def chat(self, prompt: str, *, model: str | None = None,
             system: str = "", tag: str = "") -> str:
        """One generation call. Understands a few prompt protocols (see below)."""
        model = model or settings.chat_model
        input_tokens = count_tokens(prompt) + count_tokens(system)
        self._precheck(kind="chat", model=model, n_inputs=1,
                       input_tokens=input_tokens, tag=tag)

        reply = _synthesize_reply(prompt)
        output_tokens = count_tokens(reply)

        speed = CHEAP_LATENCY_FACTOR if _is_cheap(model) else 1.0
        started = time.perf_counter()
        self._sleep((self.chat_latency_s
                     + self.per_1k_output_latency_s * output_tokens / 1000.0) * speed)
        duration = time.perf_counter() - started

        self._record(CallRecord(
            kind="chat", model=model, n_inputs=1, input_tokens=input_tokens,
            output_tokens=output_tokens,
            usd=self._usd(input_tokens, output_tokens, model=model),
            started_at=started, duration_s=duration, tag=tag,
        ))
        return reply

    # ------------------------------------------------------------------
    # internals
    # ------------------------------------------------------------------
    def _precheck(self, *, kind: str, model: str, n_inputs: int,
                  input_tokens: int, tag: str) -> None:
        """Apply injected faults. A failed call still costs you a round-trip —
        that's the whole reason a retry storm is expensive."""
        hang_for = 0.0
        with self._lock:
            if self._hang_remaining > 0:
                self._hang_remaining -= 1
                hang_for = self._hang_seconds
            fail = self._fail_remaining > 0
            if fail:
                self._fail_remaining -= 1
                code = self._fail_code

        if hang_for:
            time.sleep(hang_for)

        if fail:
            started = time.perf_counter()
            self._sleep(self.chat_latency_s if kind == "chat" else self.embed_latency_s)
            self._record(CallRecord(
                kind=kind, model=model, n_inputs=n_inputs,
                input_tokens=input_tokens, output_tokens=0,
                usd=self._usd(input_tokens, 0), started_at=started,
                duration_s=time.perf_counter() - started, ok=False, code=code,
                tag=tag,
            ))
            raise ProviderError(f"injected {code}", code=code)

    def _sleep(self, seconds: float) -> None:
        if seconds > 0:
            time.sleep(seconds)

    def _record(self, rec: CallRecord) -> None:
        with self._lock:
            self.calls.append(rec)

    @staticmethod
    def _usd(input_tokens: int, output_tokens: int, *, model: str | None = None) -> float:
        factor = CHEAP_COST_FACTOR if _is_cheap(model) else 1.0
        return (input_tokens / 1_000_000 * settings.usd_per_1m_input
                + output_tokens / 1_000_000 * settings.usd_per_1m_output) * factor

    # ------------------------------------------------------------------
    # what the tests read
    # ------------------------------------------------------------------
    def reset(self) -> None:
        with self._lock:
            self.calls.clear()
            self.client_builds = 0
        self.clear_faults()

    def calls_of(self, kind: str | None = None, *, tag: str | None = None) -> list[CallRecord]:
        with self._lock:
            out = list(self.calls)
        if kind is not None:
            out = [c for c in out if c.kind == kind]
        if tag is not None:
            out = [c for c in out if c.tag == tag]
        return out

    @property
    def call_count(self) -> int:
        with self._lock:
            return len(self.calls)

    @property
    def input_tokens(self) -> int:
        with self._lock:
            return sum(c.input_tokens for c in self.calls)

    @property
    def output_tokens(self) -> int:
        with self._lock:
            return sum(c.output_tokens for c in self.calls)

    @property
    def usd(self) -> float:
        with self._lock:
            return sum(c.usd for c in self.calls)

    def summary(self) -> dict:
        """A one-glance snapshot — the same numbers `report.py` prints."""
        with self._lock:
            calls = list(self.calls)
        by_tag: dict[str, int] = {}
        for c in calls:
            by_tag[c.tag or "(untagged)"] = by_tag.get(c.tag or "(untagged)", 0) + 1
        return {
            "calls": len(calls),
            "embed_calls": sum(1 for c in calls if c.kind == "embed"),
            "chat_calls": sum(1 for c in calls if c.kind == "chat"),
            "failed_calls": sum(1 for c in calls if not c.ok),
            "input_tokens": sum(c.input_tokens for c in calls),
            "output_tokens": sum(c.output_tokens for c in calls),
            "usd": sum(c.usd for c in calls),
            "provider_seconds": sum(c.duration_s for c in calls),
            "calls_by_tag": by_tag,
            "client_builds": self.client_builds,
        }


# ----------------------------------------------------------------------
# deterministic "model" behaviour
# ----------------------------------------------------------------------
def _overlap_score(query: str, passage: str) -> str:
    """0-10 relevance from real word overlap. Same for SCORE and SCOREMANY, so
    batching the reranker cannot change the ranking — only its cost."""
    q_words = {w for w in query.lower().split() if len(w) > 3}
    p_words = {w for w in passage.lower().split() if len(w) > 3}
    if not q_words:
        return "0"
    return str(round(len(q_words & p_words) / len(q_words) * 10, 2))


def _synthesize_reply(prompt: str) -> str:
    """Canned but *meaningful* replies, so correctness guards can be real.

    Three protocols the service uses:

      "SCORE:<query>|||<passage>"  -> a 0-10 relevance number, computed from
                                      real word overlap. Reranking therefore has
                                      a correct expected ordering.

      "SCOREMANY:<query>|||<p1>|||<p2>|||..."
                                   -> comma-separated scores, one per passage,
                                      in order. Same scoring as SCORE.

                                      Real rerank endpoints take a batch for
                                      exactly this reason: N passages scored in
                                      ONE round-trip instead of N. Parallelising
                                      N calls hides the latency; batching them
                                      removes the calls. Removing beats hiding.

      "CLASSIFY:<question>"        -> "yes"/"no" (is this answerable from docs?)
      anything else                -> a grounded answer that cites the
                                      [source: X] markers present in the prompt.
    """
    if prompt.startswith("SCOREMANY:"):
        body = prompt[len("SCOREMANY:"):]
        parts = body.split("|||")
        query, passages = parts[0], parts[1:]
        return ",".join(_overlap_score(query, p) for p in passages)

    if prompt.startswith("SCORE:"):
        body = prompt[len("SCORE:"):]
        query, _, passage = body.partition("|||")
        return _overlap_score(query, passage)

    if prompt.startswith("CLASSIFY:"):
        return "yes"

    # Pull out the cited sources and a little of the text under each, so the
    # reply length is realistic. This matters more than it looks: a docs
    # assistant's real answers run to a few hundred tokens, and those answers
    # become INPUT on the next turn of a conversation. An unrealistically terse
    # fake would hide the cost of resending a transcript entirely.
    sources: list[str] = []
    excerpts: dict[str, str] = {}
    current: str | None = None
    for line in prompt.splitlines():
        marker = "[source: "
        if marker in line:
            src = line.split(marker, 1)[1].split("]")[0].split("#")[0].strip()
            current = src
            if src and src not in sources:
                sources.append(src)
                excerpts[src] = ""
        elif current and len(excerpts.get(current, "")) < 240:
            excerpts[current] = (excerpts.get(current, "") + " " + line.strip())[:240]

    if not sources:
        return "I couldn't find that in the docs."

    cited = sources[:3]
    parts = ["Based on the documentation provided, here is what applies:"]
    for src in cited:
        body = excerpts.get(src, "").strip() or "see the referenced section"
        parts.append(f"- According to {src}, {body}")
    parts.append(
        "If this does not cover your exact situation, check the referenced "
        "documents directly, since they are the authoritative source and this "
        f"summary may omit edge cases. ({', '.join(cited)})"
    )
    return "\n".join(parts)
